version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.11"
    apt_packages:
        - openjdk-17-jre
    jobs:
        post_system_dependencies:
          - update-alternatives --config java
          - which java

python:
    install:
        - method: pip
          path: .
          extra_requirements: 
            - docs

sphinx:
    configuration: docs/conf.py
    fail_on_warning: true
