version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "latest"

python:
    install:
        - method: pip
          path: .
          extra_requirements: 
            - docs

sphinx:
    configuration: docs/conf.py
    fail_on_warning: true
