version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "mambaforge-22.9"
    jobs:
        post_create_environment: 
          #- source etc/conda/activate.d/openjdk_activate.sh
          - mamba info
          - mamba list --verbose
          - echo $JAVA_HOME

conda:
    environment: ci/python_311_dev.yaml

python:
    install:
        - method: pip
          path: .
          extra_requirements: 
            - docs

sphinx:
    configuration: docs/conf.py
    fail_on_warning: true
