version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.11"
    apt_packages:
        - default-jre

python:
    install:
        - method: pip
          path: .
        - requirements: docs/requirements.txt

sphinx:
    configuration: docs/conf.py
    fail_on_warning: true
