version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "mambaforge-22.9"
    jobs:
        post_create_environment: 
          - export JAVA_HOME="${CONDA_PREFIX}/lib/jvm"
          - export JAVA_LD_LIBRARY_PATH="${JAVA_HOME}/lib/server"

conda:
    environment: ci/python_311_dev.yaml

python:
    install:
        - method: pip
          path: .
          extra_requirements: 
            - docs

sphinx:
    configuration: docs/conf.py
    fail_on_warning: true
