#!/bin/bash

set -xeu

# copy jupyter lab config (myst == notebook)
mkdir -p "${HOME}/.jupyter/labconfig/"
cp ".binder/labconfig"/* "${HOME}/.jupyter/labconfig/"


# # pre-generate transport networks for examples
# python - <<'___HERE'
# import r5py
# import r5py.sampledata.helsinki
# import r5py.sampledata.sao_paulo
# 
# _ = r5py.TransportNetwork(
#     r5py.sampledata.helsinki.osm_pbf,
#     [r5py.sampledata.helsinki.gtfs],
# )
# _ = r5py.TransportNetwork(
#     r5py.sampledata.sao_paulo.osm_pbf,
#     [r5py.sampledata.sao_paulo.gtfs,]
# )
# 
# ___HERE
