# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:

name: Build and deploy distribution-specific packages

on:
  workflow_call:

jobs:

  build_pkgbuild_and_push_to_aur:
    name: Create an Archlinux PKGBUILD and push it to the Arch User Repository
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: 

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install build tools
        run: python -m pip install build
      - name: Build wheel(s) and packages
        run: python -m build .
      - name: Upload built packages
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist/*.*
